### ISSUE TITLE
O(n^2) time

### ISSUE THREAD

**Issue by reverofevil** [stevemao/left-pad#15]
You've opened eyes on the policies of `npm` regarding to the people who are "going to be banging on your door and taking down your accounts and stuff like that". To show my gratitude I'd like to ask you to fix an issue with `O(n^2)` execution time, e.g.

```
module.exports = function(str, len, ch) {
    return new Array(Math.max(0, len - str.length) + 1).join(ch || ' ') + str;
};
```

**Comment by Giacom** [comment]
[Isn't the current implementation the fastest due to VM optimizations? ](http://stackoverflow.com/questions/7299010/why-is-string-concatenation-faster-than-array-join)

**Comment by yhaskell** [comment]
Since this function is often used for small strings, performance testing is required to determine if this will actually not introduce performance regression on strings with length less then 10, for example. 
Then it should may be used when string is long enough.

**Comment by haoel** [comment]
1) Actually `Array.join()` has even worse performance.

2) I disagree the performance is not a matter. even for the small strings, if it is in a for-loop, it also can cause a performance issue. beside, so many other modules depend on this, if we ignore this tiny performance issue, the large-wide usage of this module also can cause big performance issue. **Please respect the engineering work even it is a very tiny work**

3) The most efficient way has been proposed, see **pull request #11**

**Comment by reverofevil** [comment]
Yeah, it's something [like 4x](http://jsperf.com/join-vs-for-1) in Chrome. Should've checked beforehand.

**Comment by dryabov** [comment]
The fastest one is `return ch.repeat($len - $str.length) + $str;` (if `String.prototype.repeat` method from ES6 is supported on the target). So, I would add a check like

``` js
if ("".repeat) {
    return ch.repeat($len - $str.length) + $str;
}
// O(log(n)) implementation
// ...
```

**Comment by benjamingr** [comment]
This can be closed at this point.
