### ISSUE TITLE
give you my support

### ISSUE THREAD

**Issue by everhopingandwaiting** [stevemao/left-pad#19]
for kik

**Comment by fergaldoyle** [comment]
I don't, don't publish something in the first place if your going to act like a little bitch and pull it afterwards.

**Comment by kaveenr** [comment]
Same here, We support you :)

**Comment by jrista** [comment]
Ditto! Far too much patent troll lawyer stick bullying going on against helpful individuals like this. Stick to your guns, Azer. 

I think pulling your modules from NPM helped expose the problem to the world, and revealed some fundamental issues with NPM's policy (and more importantly, their actual practice) on naming disputes. That kind of thing REALLY needs to be handled more carefully...what if it was the name 'left-pad' in dispute? NPM themselves would have broke the internet if they just handed it over without pause to some patent trolling company. Without due process, changing the contents of a package for a given name is a very DANGEROUS practice... You have to give people time to deprecate the package first, replace it under a different name, allow users to swap to the new module, before changing what the original module represented.

**Comment by dsernst** [comment]
This article makes you look like a badass: http://qz.com/646467/how-one-programmer-broke-the-internet-by-deleting-a-tiny-piece-of-code/

:sunglasses:

**Comment by gnzsnz** [comment]
oh yeah!

**Comment by azer** [comment]
thanks for the support :)

**Comment by KhanMaytok** [comment]
I agree with you

**Comment by CGarces** [comment]
Detailed description of the issue in Spanish.
http://barrapunto.com/comments.pl?sid=92003&cid=1374532

+1 for you and your work.
