### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by mattiasa** [stevemao/left-pad#2]
Would it be possible to add an explicit license to this project? Right now it only states BSD in the package.json file, but it doesn't state which variant of the BSD licenses nor who actually holds the copyright on the code.

We are trying to include proper licenses for all our dependencies.

Regards,
Mattias Amnefelt

**Comment by azer** [comment]
I don't care who uses and how uses it, we can consider WTF public license

**Comment by mattiasa** [comment]
In that case it would be good if you don't lie in your packaging.

**Comment by azer** [comment]
should I go over 250 packages and change each license of it to WTFPL ? I don't have time for that.
