### ISSUE TITLE
left-pad is probably not properly licensed under the WTFPL

### ISSUE THREAD

**Issue by fredjean** [stevemao/left-pad#20]
The WTFPL and current licensing practices suggest that you should include the text of the license in the package.

The [WTFPL FAQ](http://www.wtfpl.net/faq/) suggest that you should include the full text of the license into the module.

(IANAL, YMMV)

**Comment by DavidBruant** [comment]
It can be considered that @azer's intentions are clear when he chose to write "WTFPL" in `package.json`, but adding the text would be nice indeed.

**Comment by fredjean** [comment]
Indeed. It would definitively reassure organizations that are taking a prudent and conservative stance toward open source software.

**Comment by stevemao** [comment]
PR welcome :)

**Comment by cht8687** [comment]
@stevemao how about adding the "no warranty” clause in the index.js and test.js header?

**Comment by cht8687** [comment]
https://github.com/stevemao/left-pad/pull/35
