### ISSUE TITLE
benchmarks

### ISSUE THREAD

**Issue by jonschlinkert** [stevemao/left-pad#26]
@benjamingr asked me to update the benchmarks on [pad-left](https://github.com/jonschlinkert/pad-left). [Here they are](https://github.com/jonschlinkert/pad-left#benchmarks).

**Comment by stevemao** [comment]
I guess the benchmarks here can be improved here. PR welcome :)

**Comment by cht8687** [comment]
@jonschlinkert  your benchmark section seems out of date. Just wondering why you point to same repo?

**Comment by stevemao** [comment]
If there's something we can improve here, please comment or send a PR. Thanks.
