### ISSUE TITLE
Why O(log(n))?

### ISSUE THREAD

**Issue by delvedor** [stevemao/left-pad#33]
Why your code is **O(log(n))**?
Can you provide a formal proof?

**Comment by delvedor** [comment]
Nope, your code is **O(log(n))**, but concatenate a string costs **O(n)**, where **n** is the length of the final string.
This because you are not summing a number, you are copying _char by char_ the string in a new one, and this _(as far as I know)_ is an **O(n)** operation.

**Comment by stevemao** [comment]
@delvedor I think we are probably talking about the same thing. Better explanation welcome :)

**Comment by delvedor** [comment]
What I mean is:
Concatenate a string costs **O(n)**, where _n_ is the length of the final string.
**O(n) > O(log(n))** so your code is **O(n)**.

**Comment by stevemao** [comment]
[This](https://github.com/stevemao/left-pad/blob/master/perf/O%28n%29.js) is O(n). 

We have `if (len) ch += ch;` which means the`char` always tries to duplicate itself. Again PR welcome to improve the annotation @delvedor
