### ISSUE TITLE
Please add a 0.0.3 version.

### ISSUE THREAD

**Issue by ccutch** [stevemao/left-pad#5]
A dependency of babel, line-numbers is using left-pad version 0.0.3 as a dependency. Can you please add back in a 0.0.3 version to support the legacy features

**Comment by skyfarliu** [comment]
+1

**Comment by paladox** [comment]
Fails https://integration.wikimedia.org/ci/job/npm/59979/console too.

**Comment by bennycwong** [comment]
ember-cli also depends on 0.0.3 as well.

**Comment by dfalling** [comment]
+1

**Comment by walkermalling** [comment]
Clearly Github needs a `DEFCON` reaction badge.

**Comment by mattsgarrison** [comment]
+1

**Comment by jshum** [comment]
+1

**Comment by rosinscj** [comment]
+1

**Comment by kenmazaika** [comment]
:+1:

**Comment by neenhouse** [comment]
Versions 0.0.4-0.0.8 also seem to have been removed.

**Comment by geekingreen** [comment]
+1

**Comment by codeniko** [comment]
:+1:

**Comment by klejnieks** [comment]
![trash_file](https://cloud.githubusercontent.com/assets/1071064/13969436/502047bc-f059-11e5-9074-c99d665ab03f.gif)

**Comment by DannyDelott** [comment]
:+1:

**Comment by cmdln** [comment]
:+1:

**Comment by matthewhadley** [comment]
this is breaking the internets

**Comment by tavogel** [comment]
OMGPLZHALP

**Comment by derekcaneja** [comment]
:+1:

**Comment by ex3ndr** [comment]
fukfufuk

**Comment by jjshammas** [comment]
Azer right now: "HOW many people are using this 10-starred repo?!"

**Comment by guisouza** [comment]
Please I am begging you !

**Comment by travis-eh** [comment]
The sky is falling!!!

**Comment by givanse** [comment]
+1s only add noise, please refrain from doing so. This is a duplicate of https://github.com/azer/left-pad/issues/4 follow progress there.

**Comment by vhmth** [comment]
+1

**Comment by liorgiller** [comment]
:+1:  common

**Comment by dynajoe** [comment]
+1 broken!

**Comment by dynajoe** [comment]
This is what you get with a bunch of "Tiny Modules".

**Comment by tedpennings** [comment]
this has halted my day's coding mojo.

**Comment by neenhouse** [comment]
npm install left-pad@0.0.9 --save will fix your babel builds

**Comment by erykpiast** [comment]
I guess half of the world will go mad in next 24 hours.

**Comment by klejnieks** [comment]
comment from issue #4 this fixed worked for us 

"left-pad": "git://github.com/azer/left-pad.git#bff80e3ef0db0bfaba7698606c4f623433d14355"

**Comment by MylesBorins** [comment]
this is also causing lodash to break

**Comment by patrickhousley** [comment]
This just broke potentially thousands of projects.

**Comment by pbernasconi** [comment]
Causing [node-sass](https://github.com/sass/node-sass) to break too

**Comment by spinlock99** [comment]
It's really concerning that one small package could break so many projects. I'm working on an `ember-cli` app and, unfortunately, even adding `left-pad` in my dependencies won't fix this issue.

Is there really no way to install `left-pad` locally so that it will be picked up by sub-dependencies too? I've tried `npm link`ing it as well and the sub-dependency continues to fail.

**Comment by mfields-gpsw** [comment]
![](https://raw.githubusercontent.com/modcloth/hipchat-emoticons/master/src/leftshark.gif)

**Comment by jjshammas** [comment]
@spinlock99 try this in your main project package.json: "left-pad": "git://github.com/azer/left-pad.git#bff80e3ef0db0bfaba7698606c4f623433d14355"

**Comment by Blackening999** [comment]
Authors you're awesome! Killed the whole project with perhaps lest important library in the whole npm!

@spinlock99 you're totally right

**Comment by basketofsoftkittens** [comment]
+1

**Comment by binaryjohn** [comment]
+1

**Comment by loganfsmyth** [comment]
Hey all, this whole discussion is already happening in https://github.com/azer/left-pad/issues/4. The fewer places we have to use to reach people, the better, so please follow that issue.

This should now be resolved for Babel 6 if you reinstall, a Babel 5 fix is in the works.

**Comment by guisouza** [comment]
https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.fpzkdhcih

**Comment by ccutch** [comment]
btw made a pull request to no longer use this library https://github.com/lydell/line-numbers/pull/2

**Comment by ccutch** [comment]
@guisouza story sounds suspect why would he get soo butt hurt about a patent troll.

**Comment by chibicode** [comment]
Copy pasting from #4 - Thanks to @maxkostow - his fix also worked for me. 

```
npm install azer/left-pad.git#bff80e3ef0db0bfaba7698606c4f623433d14355
```

Add `--save` or `--save-dev` at the end to overwrite your `package.json`.

FYI I was deploying on Codeship but had to clear their depenency cache.

**Comment by ccutch** [comment]
Reopenning so people see this

**Comment by jamesblack** [comment]
@ccutch sounds to me like he was more irritated that NPM didn't fight the patent troll. This would piss me off...

**Comment by guisouza** [comment]
![119u2i](https://cloud.githubusercontent.com/assets/2624370/13970523/03fdc472-f068-11e5-8019-4fc4a161d8c9.jpg)

**Comment by spinlock99** [comment]
Thanks @jjshammas. My issue was that I was installing from master rather than the specific hash that you gave. Thanks again for pointing that out.

**Comment by chibicode** [comment]
Confirmed that `npm install left-pad@0.0.3` is now working

![image](https://cloud.githubusercontent.com/assets/992008/13971573/6d116d52-f04e-11e5-8d38-02ba9ce884c9.png)

**Comment by ccutch** [comment]
@chibicode thank you. Everyone who helped you are all heroes
