### ISSUE TITLE
Remove misleading "Time complexity: O(log(n))" from README

### ISSUE THREAD

**Issue by atmin** [stevemao/left-pad#50]
`str += str` is not a constant time operation. What if `str` is 1GB long?

**Comment by ddinchev** [comment]
While you are correct that the time complexity claim of `O(log(n))` is misleading, calling it a constant time operation is neither correct :)

**Comment by stevemao** [comment]
Could you find any reference to support your argument?

**Comment by peterlevi** [comment]
@stevemao Are you serious? The reference you are looking for is called CS101... The fact that something is a single statement and not a loop does not mean it is a `O(1)` operation... Think about what needs to happen internally, what is the structure in memory, and how it needs to change. In the case with string concatenation, the runtime environment needs to allocate new memory to hold the new bigger string, and then copy over the two concatenated strings over to that new memory. 

The overall complexity in your implementation is `O(n+m)` when `n` is the length of the string being left-padded, and `m` is the length of the padding. This is the theoretically optimal complexity, you cannot go lower than this as you cannot avoid the memory allocations that would take place with sufficiently large `m` and `n`. You can reduce the constant factor and the memory trashing with optimisations, but the algorithm still remains `O(n+m)`, not `O(log(n))`...

**Comment by atmin** [comment]
It's simply not possible to fill a memory region of size N in less than N steps (probably multiplied by a constant 1/8 or something, if JS engine can do that in 8-byte chunks, that depends on the processor). `memcpy` in C is also linear time operation, for example.

That said, minimizing number of operations in JS code is advantageous, because it minimizes context switching and puts less pressure on the garbage collector. So I agree with the implementation.

**Comment by peterlevi** [comment]
You probably want to also remove or change the relevant comment in the code itself.
