### ISSUE TITLE
breaking builds everywhere

### ISSUE THREAD

**Issue by didymu5** [stevemao/left-pad#6]
![](https://s3.amazonaws.com/uploads.hipchat.com/27245/3343572/Foct45xJyxhYzuL/upload.png)

**Comment by tmadison-gpsw** [comment]
https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.pykivjapt

**Comment by guisouza** [comment]
HUE BRBR !11!1!!!

**Comment by chibicode** [comment]
Copy pasting from #4 - Thanks to @maxkostow - his fix also worked for me. 

```
npm install azer/left-pad.git#bff80e3ef0db0bfaba7698606c4f623433d14355
```

Add `--save` or `--save-dev` at the end to overwrite your `package.json`.

FYI I was deploying on Codeship but had to clear their depenency cache.

**Comment by mmmeff** [comment]
I have to say, ruining everyone's day to make your political statement is kind of a shitty thing to do.

Not even Babel is installing right now.

**Comment by ghost** [comment]
I'll take over this package, so I can republish

**Comment by renatorib** [comment]
And this, guys, is how a rage can break the Internet.

**Comment by ghost** [comment]
@azer you should make @westlac the owner. He forked it and republished.

**Comment by stevemao** [comment]
I rewrote this module so it should be me :stuck_out_tongue: 
https://github.com/azer/left-pad/graphs/contributors
