### ISSUE TITLE
I'll take ownership

### ISSUE THREAD

**Issue by guyellis** [stevemao/left-pad#7]
@azer As per your post https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.tn8s3y7sp I volunteer to take ownership of this module to get it back onto Npm.

**Comment by guyellis** [comment]
I should have @mentioned @azer above.

**Comment by jonschlinkert** [comment]
why not just use an existing, supported, and more performant alternative https://www.npmjs.com/package/pad-left.

**Comment by stevemao** [comment]
I re-wrote this module so it should be me :stuck_out_tongue_winking_eye: 
https://github.com/azer/left-pad/graphs/contributors

**Comment by guyellis** [comment]
@stevemao absolutely. I just want it back on Npmjs so we can continue working. I was just offering to help.

**Comment by guyellis** [comment]
@jonschlinkert there's a whole bunch of broken dependents out there that can be fixed by getting this back on Npm.

**Comment by azer** [comment]
@stevemao just added you as owner. not sure how you can take the npm ownership tho

**Comment by jonschlinkert** [comment]
> there's a whole bunch of broken dependents out there that can be fixed by getting this back on Npm.

yeah I read more about it, I see that now. sorry for complicating the issue.

**Comment by kentfredric** [comment]
@jonschlinkert what was the primary reason for a fork? ( Was it a fork? It looks like one ).

Either way, both yours and @azer's implementations don't appear to gracefully handle the condition where the "padding string" is not exactly one character, and `left-pad` is kinda silly for using lots of concatenation where a simple `String.repeat()` would be fine.

Linked I've thrown together a slightly enhanced version of `left-pad` in this regard, including a simple test suite that will work in the browser without deps, comparing existing left-pad implementation with my suggested changes.

I don't have a dog in this fight much, so its not really worth pestering both of you with different bugs, its just a few design considerations some people brought up when we were voyueristically watching the "wow, npm does what now?" fiasco =).

Hopefully something from this is worthy of stealing by either project: https://jsfiddle.net/2n4g889u/3/

Personally, I find the over-fragmentation of components like this a little distasteful, and it seems like it would be more useful to have a general purpose String formatting module which included all the different padding/wrapping utilities.

Its "cool" to have "loads and loads of modules on NPM", but you make yourself more useful by concentrating that utility into good logical domains of concern. 

¢¢
