### ISSUE TITLE
left-pad should correctly handle Unicode

### ISSUE THREAD

**Issue by clausecker** [stevemao/left-pad#9]
One of the falsehoods programmers believe about mono-spaced typefaces is that each character occupies one column, which is terribly wrong. There are both characters that occupy zero columns (like a line-feed or combining accent characters) and characters that occupy two or more columns (like Chinese characters).

left-pad should incorporate code to correctly pad Unicode strings to the specified number of columns, even if the string contains east-asian characters.

**Comment by christianbundy** [comment]
It sounds like you're talking about [half-width and full-width forms](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms), meaning we'd need to implement something like [`wcwidth`](http://pubs.opengroup.org/onlinepubs/007904975/functions/wcwidth.html) and/or [`wcswidth`](http://pubs.opengroup.org/onlinepubs/007904975/functions/wcswidth.html).

There are a [few ports available](https://www.npmjs.com/browse/keyword/wcwidth), maybe one of these would work.

**Comment by clausecker** [comment]
Yes, these are one part of puzzle, and so are combining accents (which occupy zero columns). Both must be handled, using `wcwidth` is the right approach.

**Comment by nicbou** [comment]
An additional test with emojis or mathematical characters could and should be added, because they would fail in the current implementation.

**Comment by benjamingr** [comment]
I've worked on a proposal that had to take care of this for the ES language - I don't think left-pad should accommodate this requirement.

**Comment by nicbou** [comment]
Why was this closed? Not a bug? Not important? Fixed?
